platform :ios, '9.0'
use_frameworks!

target 'AlchemintProject' do
    pod 'Alamofire', '~> 4.7.3'
    pod 'Alamofire-SwiftyJSON', '~> 3.0.0'
    pod 'AlamofireJsonToObjects', '~> 2.4.1'
    pod 'AlamofireImage', '~> 3.3.1'
    pod 'NVActivityIndicatorView', '~> 4.3.0'
    pod 'pop', '~> 1.0.10'
    pod 'RxSwift', '~> 4.2.0'
    pod 'RxCocoa', '~> 4.2.0'
end
    
